// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function CoursesScene(Props) {
  React.useState((function () {
          return /* NotAsked */0;
        }));
  return React.createElement("div", undefined, "Courses List");
}

var make = CoursesScene;

export {
  make ,
  
}
/* react Not a pure module */
