// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Store$Lambdacademy from "../Store.bs.js";
import * as CoursesService$Lambdacademy from "../services/CoursesService.bs.js";

function CoursesScene(Props) {
  var match = React.useState((function () {
          return /* NotAsked */0;
        }));
  var setCourses = match[1];
  var match$1 = Store$Lambdacademy.useStore(/* () */0);
  console.log(match$1[0]);
  var fetchData = function (param) {
    CoursesService$Lambdacademy.fetchCourses(/* () */0).then((function (res) {
            Curry._1(setCourses, (function (param) {
                    return res;
                  }));
            return Promise.resolve(/* () */0);
          }));
    return /* () */0;
  };
  React.useEffect((function () {
          fetchData(/* () */0);
          return undefined;
        }), ([]));
  return React.createElement("div", undefined, "Courses List");
}

var make = CoursesScene;

export {
  make ,
  
}
/* react Not a pure module */
