// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as HttpClient$Lambdacademy from "../HttpClient.bs.js";
import * as Serialization$Lambdacademy from "../Serialization.bs.js";

function fetchCourses(param) {
  return HttpClient$Lambdacademy.fetchJson("/courses", undefined, undefined, Serialization$Lambdacademy.Decode[/* courseManifests */1], undefined, undefined, /* () */0);
}

export {
  fetchCourses ,
  
}
/* No side effect */
