// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function Hello(Props) {
  return React.createElement("a", {
              href: process.env.SHOWCASE_URL
            }, React.createElement("button", undefined, "Go Home"));
}

var make = Hello;

export {
  make ,
  
}
/* react Not a pure module */
