[project]
scalaVersion = "2.13.1"

[module.scala2.jvm]
root = "src"
sources = ["src"]
moduleDeps = ["utils"]
scalaDeps = {{DEPS}}

[module.utils.jvm]
root = "utils"
sources = ["utils"]
scalaDeps = [["com.lihaoyi", "pprint", "0.5.5"]]