version: '3'
services:
  api:
    restart: always
    image: 945151552117.dkr.ecr.eu-west-1.amazonaws.com/lambdacademy-back:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the temporary folder for compiled sources
      - /mnt/tmp:/usr/app/tmp
      # Mount the scala-utils volume so containers running on the host can aceess scala-utils classes
      - scala-utils:/usr/app/build/scala-utils
      # Same for shared-files
      - shared-files:/usr/app/build/shared-files
  front:
    restart: always
    image: 945151552117.dkr.ecr.eu-west-1.amazonaws.com/lambdacademy-front:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "~/.caddy:/root/.caddy"
volumes:
  scala-utils:
    external:
      name: "scala-utils"
  shared-files:
    external:
      name: "shared-files"