version: '3'
services:
  backend:
    image: 945151552117.dkr.ecr.eu-west-1.amazonaws.com/lambdacademy-back:semaphore-setup
  redis:
    image: 945151552117.dkr.ecr.eu-west-1.amazonaws.com/lambdacademy-back:semaphore-setup
    ports:
      - "80:80"
      - "443:443"