version: '3'
services:
  api:
    image: 945151552117.dkr.ecr.eu-west-1.amazonaws.com/lambdacademy-back:latest
  front:
    image: 945151552117.dkr.ecr.eu-west-1.amazonaws.com/lambdacademy-front:latest
    ports:
      - "80:80"
      - "443:443"