addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.2.1")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.10")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.5.0")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt" % "6.2.0")