// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Hello$Lambdacademy from "./components/Hello.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Hello$Lambdacademy.make, { }), "app");

export {
  
}
/*  Not a pure module */
