// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";

function courseManifest(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.string, json),
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* description */Json_decode.field("description", Json_decode.string, json),
          /* tags */Json_decode.field("tags", (function (param) {
                  return Json_decode.list(Json_decode.string, param);
                }), json)
        ];
}

function courseManifests(param) {
  return Json_decode.list(courseManifest, param);
}

var Decode = /* module */[
  /* courseManifest */courseManifest,
  /* courseManifests */courseManifests
];

export {
  Decode ,
  
}
/* No side effect */
