// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

var initial = /* record */[/* courses : NotAsked */0];

function reducer(state, action) {
  if (action) {
    return /* record */[/* courses */action[0]];
  } else {
    return state;
  }
}

var State = /* module */[
  /* initial */initial,
  /* reducer */reducer
];

var Effects = /* module */[];

var ctx = React.createContext(/* tuple */[
      initial,
      (function (_action) {
          return /* () */0;
        })
    ]);

var provider = ctx.Provider;

function Store$Provider(Props) {
  var children = Props.children;
  var match = React.useReducer(reducer, initial);
  return React.createElement(provider, {
              value: /* tuple */[
                match[0],
                match[1]
              ],
              children: children
            });
}

var Provider = /* module */[
  /* ctx */ctx,
  /* provider */provider,
  /* make */Store$Provider
];

function useStore(param) {
  return React.useContext(ctx);
}

export {
  State ,
  Effects ,
  Provider ,
  useStore ,
  
}
/* ctx Not a pure module */
